language: python
python:
  - "3.8"
before_install:
  - sudo apt-get install python3-gi
install:
  - pip3 install -r requirements.txt
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-gi gir1.2-ibus-1.0 gir1.2-wnck-3.0 
install:
  - pip3 install -r requirements.txt
script:
  - pytest
 
