language: python
python:
  - "3.2"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-gi gir1.2-ibus-1.0 gir1.2-wnck-3.0 
install:
  - pip3 install -r requirements.txt
script:
  - pytest
 
